# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java Buid

on:
  push:
    branches-ignore: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Setup settings.xml 
      uses: s4u/maven-settings-action@v3.0.0
      with:
        githubServer: false
        servers: |
           [{
              "id": "github",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.MAVEN_REPO_READ }}"
           }]
#    - name: echo settings
#      run:  cat /home/runner/.m2/settings.xml
    - name: git
      run: git --version

