# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java Buid

on:
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
    - uses: actions/checkout@v3
    - name: git
      run: git --version
    - name: Git Tag
      run: |
        #get version in pom.xml
        version=$(mvn exec:exec -Dexec.executable=echo -Dexec.args='${project.version}' --quiet -N | sed 's/-SNAPSHOT//')
        date=$(date '+%Y%m%d')
        buildnr=$1
        newversion="$version.$date$buildnr"
        echo "Tagging version  $newversion"
        remote=$(git remote)
        git tag "$newversion"
        git push "$remote" "$newversion"
        
